//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::models::Entity as Models;
pub use super::conversations::Entity as Conversations;
pub use super::messages::Entity as Messages;
pub use super::settings::Entity as Settings;
